# Generated by Django 2.1.7 on 2019-02-26 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_no', models.IntegerField(default=None)),
                ('journey_date', models.DateField(default='26-02-19')),
                ('journey_time', models.TimeField(default='00:00:00')),
            ],
        ),
        migrations.CreateModel(
            name='bus',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_no', models.CharField(default='', max_length=15)),
                ('bus_type', models.CharField(choices=[('a', 'ac'), ('n', 'none-ac')], default='', max_length=1)),
                ('bus_capacity', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='bus_route',
            fields=[
                ('bus_route_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.bus')),
            ],
        ),
        migrations.CreateModel(
            name='cancellation',
            fields=[
                ('can_id', models.AutoField(primary_key=True, serialize=False)),
                ('can_date', models.DateField(default='26-02-19')),
                ('refund', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=25)),
                ('email', models.EmailField(default='', max_length=30)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='', max_length=1)),
                ('contact_no', models.CharField(default='', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='myadmin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('adminname', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=25)),
                ('email', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('deapture_station', models.CharField(default='', max_length=30)),
                ('arrival_station', models.CharField(default='', max_length=30)),
                ('pickup_station', models.CharField(default='', max_length=30)),
                ('distance', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField(default='00:00:00')),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.bus')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.route')),
            ],
        ),
        migrations.CreateModel(
            name='waiting',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_no', models.IntegerField(default=None)),
                ('journey_date', models.DateField(default='26-02-19')),
                ('journey_time', models.TimeField(default='00:00:00')),
                ('c_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myadmin.customer')),
                ('t_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myadmin.timetable')),
            ],
        ),
        migrations.AddField(
            model_name='cancellation',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.customer'),
        ),
        migrations.AddField(
            model_name='bus_route',
            name='r_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.route'),
        ),
        migrations.AddField(
            model_name='book',
            name='c_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myadmin.customer'),
        ),
        migrations.AddField(
            model_name='book',
            name='t_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myadmin.timetable'),
        ),
    ]
