# Generated by Django 2.1.7 on 2019-02-26 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='bus_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myadmin.bus'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='route_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myadmin.route'),
        ),
    ]
