# Generated by Django 2.1.7 on 2019-02-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20190226_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='bus_id',
            new_name='b_id',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='route_id',
            new_name='r_id',
        ),
    ]
