# Generated by Django 2.1.7 on 2019-03-04 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_auto_20190226_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiting',
            name='journey_time',
        ),
        migrations.RemoveField(
            model_name='waiting',
            name='seat_no',
        ),
        migrations.AlterField(
            model_name='book',
            name='journey_date',
            field=models.DateField(default='04-03-19'),
        ),
        migrations.AlterField(
            model_name='cancellation',
            name='can_date',
            field=models.DateField(default='04-03-19'),
        ),
        migrations.AlterField(
            model_name='waiting',
            name='journey_date',
            field=models.DateField(default=datetime.date),
        ),
    ]
