# Generated by Django 2.1.7 on 2019-03-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_auto_20190304_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='journey_date',
            field=models.DateField(default='04-03-19'),
        ),
    ]
