# Generated by Django 2.1.7 on 2019-03-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_auto_20190304_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='journey_date',
            field=models.DateField(default='11-03-19'),
        ),
        migrations.AlterField(
            model_name='cancellation',
            name='can_date',
            field=models.DateField(default='11-03-19'),
        ),
        migrations.AlterField(
            model_name='waiting',
            name='journey_date',
            field=models.DateField(default='11-03-19'),
        ),
    ]
