# Generated by Django 2.1.7 on 2019-03-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_auto_20190310_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='seat_no',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
