# Generated by Django 2.1.7 on 2019-03-31 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_auto_20190310_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_no', models.CharField(default='', max_length=20)),
                ('cvc', models.CharField(default='', max_length=10)),
                ('amount', models.IntegerField(default='')),
                ('c_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myadmin.customer')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='journey_date',
            field=models.DateField(default='31-03-19'),
        ),
        migrations.AlterField(
            model_name='cancellation',
            name='can_date',
            field=models.DateField(default='31-03-19'),
        ),
        migrations.AlterField(
            model_name='waiting',
            name='journey_date',
            field=models.DateField(default='31-03-19'),
        ),
    ]
